version: "3.7"

services:
  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app-network
  server:
    build: ./server
    command: node /usr/dist/bundle.js
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
